global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          group: 'prometheus'

  - job_name: 'smart_device'
    static_configs:
      - targets: ['172.20.10.4:8010']
        labels:
          group: 'dev'

  - job_name: 'linux'
    static_configs:
      - targets: ['172.20.10.4:9100']
        labels:
          group: 'dev'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.1.118:9093']

rule_files:
  - node_down.yml
  - memory_over.yml